// react-crash-course/src/components/Button.js
import PropTypes from 'prop-types'

const Button = ({color, text}) => {
    return  <button style={{ backgroundColor: color }}className="btn">{text}</button>
}

Button.defaultProps = {
    color: 'steelblue'
}

Button.propTypes = {
    text: PropTypes.string,
    color: PropTypes.string
}

export default Button

// vue-crash-course/src/components/Button.vue
<template>
    <button @click="onClick()" 
    :style="{ background: color}" 
    class="btn">{{ text }}
    </button>
</template>

<script>
export default {
    name: 'Button',
    props: {
        text: String,
        color: String,
    },
    methods: {
        onClick() {
            this.$emit('btn-click')
        },
    }
}
</script>
